### ISSUE TITLE
A roadmap for Node.js security

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/security-wg#101]
Hey All,

@mikesamuel, a security researcher from Google, has put together a ["Security Roadmap"](https://nodesecroadmap.fyi/) which outlines some best practices that companies + individuals can use when developing and deploying Node.js applications. It is 50+ pages and has had quite a bit of care put into it.

I'm opening this issue to discuss the roadmap in depth with that team before we do any sort of comms push around this, looping in the foundation marketing team and some of our resources over at google to get this in front of people.  Before doing any public push we would like the @nodejs/tsc and @nodejs/security-wg to take a look and make sure there isn't anything major problems with this being shared en masse.

FWIW, [security roadmap](https://www.google.com/search?q=security+roadmap&oq=security+roadmap) is an industry standard term (I originally was like... we don't do roadmaps 😉)

>A security roadmap is a powerful tool for aligning security processes with business requirements and goals, and improving the general efficacy of the security program

**Comment by vdeturckheim** [comment]
Looks a bit like the ebook I wrote: Node.js security checklist ^^ https://www.sqreen.io/resources/nodejs-security-handbook

**Comment by mikesamuel** [comment]
@vdeturckheim Thanks for the pointer.  Your ebook looks like fine advice for those deploying on a Node.js stack.

The roadmap is less focused on what to do with the platform as it is today and more focused on how to change the platform so that systems built on it are more secure & robust.

IOW, how to
1. evolve the platform so that existing practices lead to more secure systems,
2. provide idioms so that the easy way of expressing an idea is also a secure way,
3. change tools so that less effort is required to address a class of threats where
   some per-project effort can't be avoided.

**Comment by MylesBorins** [comment]
We would like to approach the foundation about promoting this document, are there any objections?

**Comment by vdeturckheim** [comment]
@MylesBorins fwiw lgtm :) However I did not read it cover to cover yet :/

**Comment by TobiasWehrum** [comment]
I'm sorry that this is a bit off-topic, but do you have an updated link for your PDF, @vdeturckheim? It sounds like an interesting resource and it seems like it got lost in the Datadog merge.

**Comment by vdeturckheim** [comment]
Sadlu I'm not sure it still exists, the CTO oriented version has some similar content and is open source however https://github.com/sqreen/CTOSecurityChecklist

**Comment by mikesamuel** [comment]
https://github.com/google/node-sec-roadmap
