### ISSUE TITLE
Can we have "unsecure" features in Node.js?

### ISSUE THREAD

**Issue by aduh95** [nodejs/security-wg#1274]
Should there be a note about security in the docs? Specifically, I am wondering what would constitute a vulnerability here.

_Originally posted by @tniessen in https://github.com/nodejs/node/issues/45096#issuecomment-2037169224_

In the PR linked above, I'm suggesting adding a static HTTP server that is targeted for development only, i.e. not meant to be production ready (ever, likely). Is there a way to make sure that bugs that will be found in this implementation will not result in security releases?
I think there is value to have this feature built-in (it's already available via npm packages, but having to add a dev dependency for such a simple feature seems silly), but it's unclear if it's worth it if it results in a flow of security vulnerability reports.

**Comment by mhdawson** [comment]
I'll be interested in listing to the discussion in the meeting since I can't make it. My first thought is that it will be a challenge to community/explain/justify why we exclude some parts of our APIs from vulnerability reports.  We had discussion around doing so for experimental features and the consensus was that it was not the way to go at that point in time.

**Comment by marco-ippolito** [comment]
I don't think it's a good idea to provide insecure features in core.

We will receive issue, and h1 reports even if we mark it as insecure, because users will rely on the feature and build products and libraries on top.

I think the expectation is that if something is stable, is secure for production.
A insecure feature would be something forever experimental.
I believe that would be more useful as a separate npm package.
