### ISSUE TITLE
Security Mailing List

### ISSUE THREAD

**Issue by RedYetiDev** [nodejs/security-wg#1343]
Currently, the alias <security@nodejs.org> forwards to <nodejs-79566c66a30b0312@forwarding.hackerone.com>, which will open a HackerOne report. I recommend updating this alias to forward messages to all members of the security team, similar to how other aliases function.

One enhancement is that when security emails not warranting a report are received, individual members can respond rather than a hackerone report being made. (And when a report is needed, members can still create it)

Another enhancement is that individuals with specific concerns are able directly contact the entire security team. For instance, triagers could inform the team about premature disclosures more effectively, and users could inquire about their own premature disclosures if needed.

**Comment by tniessen** [comment]
I assume this issue was opened in good faith but it seems misguided.

This security team is _not_ responsible for handling reports of security vulnerabilities, and in fact _should not_ have access to reported vulnerabilities.

**Comment by RedYetiDev** [comment]
What about premature disclosures, isn't that the security team's jurisdiction?

**Comment by tniessen** [comment]
Are you suggesting to repurpose the email alias from reporting vulnerabilities to allowing people to privately communicate with the security team? The security team doesn't have access to H1 reports and wouldn't be able to answer questions about their status. In any case, it'd seem safer to create a new list or alias for that.

**Comment by RedYetiDev** [comment]
> it'd seem safer to create a new list or alias for that.

Sounds good to me, I'm suggesting an email alias in general, doesn't have to be the one I mentioned in my issue.

**Comment by mhdawson** [comment]
I'm not sure a new list makes sense.

The security wg is more about initiatives around improving security within the projects versus handling security reports.

Any communicating related to a security report should go through H1. Premature disclosures fall into this category and are not in the scope of the security-wg.  For premature disclosures I would just use the email tsc@iojs.org reporting that and that the issue needs to be moved.

Otherwise if its something that can be discussed in public it either should be an issue in the nodejs/node repo or the nodejs/security-wg depending on the topic.

I don't think we want an email for the security-wg.
