### ISSUE TITLE
Name this Working Group

### ISSUE THREAD

**Issue by rvagg** [nodejs/security-wg#4]
As raised by @Trott in https://github.com/nodejs/security-wg/pull/2#issuecomment-263686173, "Node.js Security Working Group" might not be the best name as it may lure people to think that they should report issues via the issue tracker here.

So, one of the first jobs of the group forming here is to decide on the name, both the full name and the repository name.

**Comment by joshgav** [comment]
Thinking and thinking, **Security** seems the most concise and descriptive title for what this WG proposes to do. Other suggestions that come to mind include:

* **Trust** - because the goal of better security policy is to promote trust. But it doesn't tell much about what this WG proposes to do.
* **Security Policy** - because this group is about managing security rather than security itself. But that's not really true, it's also an advisory group for security itself.
* **Vulnerability** - because a prime job will be managing policy and process for vulnerabilities. But that's a negative name and also only part of the proposed scope.

So I think we should call this group Security as proposed, and **rename the private group** as *Disclosures* or *Vulnerabilities*.

@rvagg @Trott 

> it may lure people to think that they should report issues via the issue tracker here

We could have a big (blinking!) banner on the README and in the issue and PR templates redirecting people to the Disclosures email for actual vulnerability reports. Seems that would be sufficient diligence.

**Comment by gibfahn** [comment]
+1 to `Security WG` for this group and `Vulnerabilities` for the private one.

The private group is only used for reporting vulnerabilities right? So that name really makes more sense. (IMHO)

**Comment by williamkapke** [comment]
At NINA, there was positive opinion towards the existing one being called the `Security Response Team` (it isn't a Working Group)

My opinion is that the new group should be called the `Node Security Committee` which oversees the `Node Security Project`... along with the other proposed security activities.

**Comment by sam-github** [comment]
I like the names proposed in https://github.com/nodejs/security-wg/issues/4#issuecomment-274186359, with the caveat that we most emphatically do *not* oversee the _Node Security Project_, that is an existing project, not ours, we shouldn't steal its name, and the name wasn't given to use. The group will oversee a Node Foundation Vulnerabilty Database (seeded with a donation from `nsp`).

**Comment by sam-github** [comment]
Any other thoughts, @nodejs/security-wg ?

**Comment by drifkin** [comment]
👍 to `Security Response Team` and `Node Security Committee`. I think it makes things more clear.

**Comment by sam-github** [comment]
I don't think there is any appetite to rename this from "Security WG", though perhaps if the security response team at-nodejs/security gets reorganized the issue will come up again.

Shall we close for now if there isn't something actionable?
