### ISSUE TITLE
Should discussion about Node.js core issues occur more on H1 than in nodejs-private?

### ISSUE THREAD

**Issue by sam-github** [nodejs/security-wg#500]
I'm moving this discussion from https://github.com/nodejs-private/security/issues/215. I know that link and some others here won't be visible to many people, sorry, but this is in part a discussion of how to enable appropriate visibility to sec discussions after-the-fact. I can't see all the links I include here, either (like the H1 link).

Right now initial reports from the public are in H1 and initial reports by the node core team (happens pretty often that @mcollina for example sees a problem with a node API, and opens an issue and fix for it) are directly reported to nodejs-private/security. For H1, the report contents are copied into a nodejs-private/security.

After that, AFAICT, all discussion is in nodejs-private/security (or nodejs-private/node when its about the PR that fixes the issue).

This could be seen as convenient for us, since we spend so much time in github, but:
- it means the conversation can never be made public, post release
- it leads to [links](https://github.com/nodejs/node/commit/b77f699) in our public record that can't be followed by most people

On the other hand, an issue with using H1 for more of the conversation is that only the initial triage team can see it, this link is only visible to a small handful of people:
- https://hackerone.com/bugs?report_id=453513 (from - https://github.com/nodejs-private/security/issues/214#issue-386448538)

Its actually a nice feature, limiting the view to an "as needed" basis, but if more conversation happens there, then the initial triage team would have to explicitly add more people to the bug as they thought appropriate. 

Also, its not clear to me whether any of the reports are ever made public. I can't find any on https://hackerone.com/nodejs, and I don't have enough permission to access H1 and see if there are reports there that have been fixed but not released.

Despite these minor issues, the current process works OK, for us, and I'm a bit hesitant to suggest changing it if it makes the process harder to deal with for the people fixing issues.

That said, my ideal process would result in as much conversation as possible becoming available for public review ***after the release***, to keep our process as open and transparent as possible, but not reveal details of unfixed bugs.

To do that, we'd need:
- more conversation on H1, with more (relevant) people added to the discussion - perhaps everyone who can view nodejs-private/security should be explicitly added to H1?
- a private nodejs-private/node-XXXX (where XXXX is a H1 issue ID, if such exists) spun up per issue, where the fix (or fixes, often there are multiple PRs when the fix needs backporting to older release lines) can be PRed and discussed.

Post-release, I'd then make the H1 conversation public, and I'd link to the H1 conversation in the node.js security release announcement. Note that when posting in H1, its possible to make comments that can be viewed by the reporter of the issue, but sensitive not-to-be-public comments are also possible. I _assume_ (not actually certain), that even after publicization, those internal comments would not be viewable.

I'd also make the nodejs-private/node-XXXX repo public, perhaps the repo could actually be moved to a public org? This would allow the PR conversation to be public after the fact.

If this is unreasonable because of its goals, or the burden on @nodejs/security , then at the least we should make sure that H1 reports from external users have their state updated when fixes for the issues are released (maybe we do this already, as I said, I can't tell).

Any other thoughts? I think a number of people watching the security-wg repo are consumers of node.js sec releases, but don't have visibility, even after the fact, to how they are made.

**Comment by rvagg** [comment]
Transparency is a nice goal, but the main one I care about is having enough eyes on security issues to have meaningful discussion and quality fixes. Engagement from nodejs/security has not been improving, it's getting worse if anything and it puts a heavy burden on a very small number of people to get thing right and that puts quality and ultimately end-user security at risk. Dealing with incoming reports involves:

* Initial discussion to assess whether something should be treated as a privately-handled security concern
* The nature of the problem and how to communicate to the public (naming, categorising, CVEs, descriptions pre and post disclosure)
* Coming up with code fixes

Don't be fooled by the "Attribution" I've been putting into security announcements, there's a _very_ small number of people doing this work.

If we move more to HackerOne will that exacerbate the problem or improve it?

This might be appropriate for a separate issue, but it would help with my concerns of limiting the pool even further: maybe such a move is time to revisit the ongoing discussion about who gets to be in nodejs/security and how we assign trust. TSC members are increasingly stretched too thin to do much meaningful work outside of their own little interest areas so maybe relying on them for this task is an error? We've expanded nodejs/security a little, but it's been so hard to do that because of the trust problem. If you work for an IBM or Microsoft it's a bit easier because you have contractual trust obligations and can be held to account. But that still provides a limited pool.

**Comment by mcollina** [comment]
I’m of the opinion that we should expand @nodejs/security. We can follow the same approach of @nodejs/build where somebody has to refer somebody else. We should also scout for specific areas that are not covered.

I’m also +1 on moving to h1 for the issue handling, our private repo is not getting enough attention.

**Comment by Trott** [comment]
> I’m of the opinion that we should expand @nodejs/security. We can follow the same approach of @nodejs/build where somebody has to refer somebody else. We should also scout for specific areas that are not covered.

Refs: https://github.com/nodejs/security-wg/blob/38b69077b570f79eb900fec24dba8afebb246519/processes/security_team_membership_policy.md

IIRC, while authored by the Security WG, significant changes to that doc would have to be approved by TSC (as authority over the processes around security-in-core was not delegated to the Security WG), Adding a sentence to that effect to that doc would be 👍.

**Comment by sam-github** [comment]
> Transparency is a nice goal, but the main one I care about is having enough eyes on security issues to have meaningful discussion and quality fixes.
...
> If we move more to HackerOne will that exacerbate the problem or improve it?

I share this concern. The number of active members (people willing to work on or comment on PRs/issues regularly and fairly promptly) of @nodejs/crypto and @nodejs/security is smaller than desireable.

The H1 initial triage team is right now quite small, but could be expanded to include @nodejs/security. It started off small, and I think I might have recommended this (it was a long time ago and my memory was poor), because at one point there was some concern about the size of @nodejs/security.

I think H1 has the potential to improve engagement, because it allows arbitrary people with relevant expertise to be added to the discussion on *that one issue*, so we can pull people in easily, without having to open up the entire nodejs-private issue tracker, repo, all of H1, etc. For example, the hash seed conversation could be opened to more V8 team members (node and google), or the recent PR (that ended up public, so it wasn't an issue) on crypto IV problems could have had @tniessen pulled in.

On the other hand, if people are comfortable just increasing the size of @nodejs/security, then using H1 won't help (or hinder, AFAICT) participation, unless current members don't like using it, and disengage more. That would be a worst-case outcome.

Doing more work in nodejs/node would also increase engagement, the pool of people who can contribute is much wider there. That won't be possible for everything, but is a good reason to try to get things public if at all possible.

**Comment by mcollina** [comment]
I'm +1 in increasing the size of @nodejs/security.

**Comment by mhdawson** [comment]
I'm in favor of increasing the number of people who can help with core security vulnerabilities.  @rvagg do you have candidates that you think we should be considering now?

The other question is whether we try to push more discussion into H1 or not.  The right answer might still be a mix of both but some guidelines on when we should use one versus the other might help.  @sam-github did you have any thoughts on that front or were you thinking it was one or the other?

**Comment by sam-github** [comment]
If its a vulnerability that should be discussed privately, H1.

If it isn't a vulnerability, why would the discussion be private? Sec releases (since they directly reference vulns) need discussion in private, but skimming the top couple pages of nodejs-private/security/issues, it looks like most non-vulns are discussions that could just have well been in nodejs/security-wg, or nodejs/TSC, or somewhere public.

Again, I'm not trying to push this down anybodies throats. If people don't want to change the existing process, or think a process change will decrese engagement, we can keep going with what we have. My hope is that we can get more engagement by making the output more public (after the fact), by doing more work in the open (if its not sec-critical), and by looping more people into H1 issues when they have specific expertise.

In that case I'll PR issue templates to the nodejs-private/security repo and generally try to do some cleanup there.

**Comment by rvagg** [comment]
We kept HackerOne membership low because triage has always been low, that's not our critical point and never has been (aside from a couple of no-response-in-24-hours reports). I still think that too many fingers on triage is a bad thing, it's the next part of the funnel that's the problem. Perhaps that can be controlled within HackerOne?

And no, I don't have candidates in mind for expansion unfortunately. Perhaps @nodejs/security-wg can help come up with criteria that establish enough trust (internally and externally via public perception). Maybe we just need to put out a call and review names as they come in! People that have enough mental bandwidth to be active on nodejs/node are good candidates, the trust issue is the problem though.

**Comment by sam-github** [comment]
H1 is going to be used to discuss vulns, and the github private repo with sec issues is getting archived.
