### ISSUE TITLE
.travis.yml references an EOL node version

### ISSUE THREAD

**Issue by dominykas** [nodejs/security-wg#684]
I was going through `.travis.yml` across the org to look for outdated Node.js versions and spotted this repo referencing `8.9.0`. I figure it needs a bump?

Not sure what this is used for - is it meant to be testing in a single version? If so - might make sense to just change the version to `lts/*` or `latest`. If it's meant to test in multiple versions - it may be worth using one of the shared configs at https://github.com/nodejs/ci-config-travis to automatically include new versions?

Happy to PR, if needed.

**Comment by DanielRuf** [comment]
Hm, it seems we have to fix the tests because there are some failing ones but the test suites are still green / ok.

Pinging @lirantal as he was maybe the last one working on this.

https://travis-ci.com/github/nodejs/security-wg/builds/179574346
https://github.com/nodejs/security-wg/tree/master/__tests__/tools

A PR should be ok.

**Comment by dominykas** [comment]
Change to `latest` or use a shared config for LTS versions 8+?

**Comment by DanielRuf** [comment]
> Change to just `lts/*`

This is probably fine.
