### ISSUE TITLE
Review of impact of network based imports

### ISSUE THREAD

**Issue by bmeck** [nodejs/security-wg#755]
We have a [PR for `https:` and loopback `http:` imports against Node core](https://github.com/nodejs/node/pull/36328). This has spawned various discussions in https://github.com/nodejs/node/discussions/36430#discussioncomment-753311 around robustness and security impact; however, it would be prudent to have a review of what this would mean for the security workflows in the existing ecosystem and potential needs in order to satisfy various discussion points. To that end, I am asking for review of the discussions and potentially help in filling out a list of implementation concerns for the ecosystem and supply chain in particular for these network based imports.

We are expanding 2 documents right now with [use cases](https://docs.google.com/document/d/12OspzW8aK7-WUiyBkjyrGpQy3ChXU-WnztcSY5rph8I/edit#) and [implementation security](https://docs.google.com/document/d/1tS80LmzraV4yXEYIQ-fWaCm2MIpXfbtrSYjsI8kWKko/edit) however these lack the general ecosystem and supply chain scope. I am hoping to make a new document and/or amend those documents with an initial review prior to merging the PR into Node core.

**Comment by vdeturckheim** [comment]
Putting on my security hat here :)

I see two main security questions with HTTPS imports:
* Threat model user understanding
* Auditability

**Threat model user understanding**
End users are not always aware of all potential security impacts and features. But this should not prevent feature from being shipped. It however means we need 3 things:
* Secure defaults (e.g. we can enable http imports, but by default, https imports must be enforced)
* Practical documentation: in these cases doc should say "the best practice is to use it like X because Y" and making sure user know about the security features they can use

**Auditability**
One should be able to know why a package is here. In a way, lockfiles are good to know what should be here and what should not. Even if it is not directly needed for the experimental time, it probably will be in the checklist to move to stable.

Also, the question I may have is about authentication and privacy. Is there a way to use https imports with authentication? The first topic in the security doc is about tracking through https insertion, this is a good point but even only a server-side analytics tool could unleash a lot of secrets.

**Comment by bmeck** [comment]
> Is there a way to use https imports with authentication?

This seems like the only actionable thing outside of just filling out stuff during experimental itself.

### Certs:

Right now you can setup the root certs allowed for Node and we could reject on the basis of certs that are not based off the root certs and/or certs that are not explicitly listed to be allowed. This seems also useful outside of the imports feature to prevent exfiltration.

### Address ranges:

We have block lists in core and we could have an accept list as well for valid connection targets when using HTTPS in general. We actually do this for the loopback exception that allows `http:` in the PR.

### Headers!

For loading you might want to set custom headers: Authorization, Cookie, etc. I am neutral on how we supply this but I don't think it should be mutable by the user at runtime. We could just throw this into policies but since policies are just for loading mechanisms currently it would not affect normal HTTP/S calls from builtins. The problem with having this one in particular be exposed to normal builtins is how leaky the HTTP agents are built in node currently I do not think we could easily keep the secrets provided by them safely away from user inspection. For loading, we likely can get away with running the HTTP/S requests on an entirely separate thread to avoid exfiltration via things like reflection.

----

For all 3 of these I'm not sure we should scope them to the import functionality itself but might be blockers for going out of experimental. I do think headers would be non-trivial to fix for non-loader based workflows though and likely would end up tied to loaders.

I do have concerns about things that are not using the same auth mechanism since you can imagine people loading adjacent resources from the network via HTTP/S and import.meta.url.

> The first topic in the security doc is about tracking through https insertion, this is a good point but even only a server-side analytics tool could unleash a lot of secrets.

Are we talking about ways to exfiltrate the data? I agree that this is already possible with other means, but the document is about what is possible with the new capabilities provided by HTTPS imports not around all possible security concerns. I'd like to keep feedback scoped to the new import functionality.

**Comment by vdeturckheim** [comment]
Agreed, none of this should be blockers for the experimental phase. I'll be meaner for getting to stable ;)
Thanks a lot for the hard-work @bmeck !
