### ISSUE TITLE
👋 Open call for discussion to suggest focus areas for Security WG 

### ISSUE THREAD

**Issue by lirantal** [nodejs/security-wg#771]
Hi everyone,

In its incumbent, the Node.js Security working group was chartered to triage and manage ecosystem security vulnerabilities to the scope of anything within the npm package registry. It had also worked on defining and refining some security-related workflows, such as the suggested `SECURITY.txt` per repository.

Since then, things have evolved and the [ownership of triaging ecosystem vulnerabilities has been moved outside this working group](https://nodejs.medium.com/node-js-ecosystem-vulnerability-reporting-program-winding-down-591d9a8cd2c7) due to the lack of capacity to handle them.

Given that, I'd like to create a call for open discussion as to where and what would this working group focus on next? Should it still exist? should it merge/concede to the OpenJS Security working group?

**Comment by lirantal** [comment]
@DanielRuf what's a good way to support them? most of the time now, reporting vulns doesn't come through us so we're members of this WG are "in the dark" about them. From experience of training these reports before, those who submit the report help the maintainer confirm if the fix is correct or not so they take care of that aspect of it at least.

**Comment by DanielRuf** [comment]
> maintainer confirm if the fix is correct or not so they take care of that aspect of it at least.

At least they often confirm if the initial problem is mitigated but often there are cases like in `keypair` where the fix introduces new problems or does not cover everything.

Most reporters are not developers afaik and in the other security team we (the security team) are part of the vulnerability handling like this:

person A reports security problem => internal ticket is created and reviewed => contact to maintainer => if maintainer provides patch, create private GH repo, add the changes as PR, we do a review and provide the suggested changes to the maintainer; otherwise we create private GH repo, create the patch and discuss in the team and then provide the patch files to the maintainer

> reporting vulns doesn't come through us so we're members of this WG are "in the dark" about them

True. But where can we help?

Code reviews / patch reviews for sure.

Maybe also help projects to create the needed security.md file and process(es) to make communication easier.

Work on guides for recommended code solutions per problem or make such guides more visible (the ones from nodej.org are not so many and not so actively advertised or well-known).

Cooperate with the Linux/Node/... Foundation to get more participants for the security surveys in the JS ecosystem (I've received an email from them in this case).

Anything that makes life better for maintainers (for example CodeQL actions, guides, support with patch creation and review, ...), to promote awareness or to make important updates more visible. For example retrieving updates from npmjs.com/advisories (not sure where this is promoted or linked) is not that easy.

**Comment by fraxken** [comment]
Hello 👋

It's really hard to find ideas that are actionable by a group 😵.

---

On my side, I do my best to push security resources in French and help people in local Slack/Discord communities. The language barrier can be an obstacle to security if everything is in English!

At the beginning of the year I published a Node.js [ebook](https://docs.google.com/document/d/1JHgmEFkc8Py4XSuCB8_DQ5FFEJoogyeninFK6ucTd4o/edit?usp=sharing) of 103 pages in French with a whole section on security (Thanks to @vdeturckheim who made a review). I've had a lot of positive feedback and a lot of developers have told me that they've learned about security through this.

This is obviously an individual action. I guess this goes along with the argument for more guidance.

---

Maybe we can build tools that would help maintainers in some way? This is what we try to do on [NodeSecure](https://github.com/NodeSecure) but I don't always feel like talking about it (I figure it's not necessarily directly related to the group... Perhaps I am too reserved 😳.).

--- 

For OpenJS Security WG i'm a bit lost about who they are and the goal of this group (I guess I'm missing some information, is there a page to know?). I'm on the OpenJS Slack and to be honest I don't feel that it is more active.

If merge can bring more value to the Node.js ecosystem then I am in favor of it.

**Comment by UlisesGascon** [comment]
Hello All!

I agree with you. I see two clear paths also:

- **Support maintainers** in terms of patching/review/advice or even providing tools/resources

- **Spread the knowledge** across maintainers and users, but I agree with @lirantal regarding the time investment.

On a personal side I will love to be more active and provide more support to the WG.

**Comment by lirantal** [comment]
@fraxken thank you for sharing all that and for coming up with that Node.js ebook. I can't read French but it looks great! :-)

I think there definitely needs to be a security setting at the OpenJS Foundation level, but what exactly would it scope in terms of the charter is what I find that we don't really grasp yet. cc @joesepi with regards to recent conversations we've been exchanging on similar topics.
