### ISSUE TITLE
"Responsible" vs "Coordinated" disclosure

### ISSUE THREAD

**Issue by JLLeitschuh** [nodejs/security-wg#778]
"Responsible" in the discussion of vulnerability disclosure is an outdated term. For this discussion I'm referring to this policy here: https://github.com/nodejs/security-wg/blob/main/processes/responsible_disclosure_template.md

"Responsible" implies a set of ethics and morals are involved in vulnerability disclosure. "responsible" is also very subjective. From the perspective of the security researcher, the company (in this case GitHub) may be the "irresponsible" party for releasing the vulnerable code without adequate testing. From the perspective of the company, in this case GitHub, the researcher may be "irresponsible" if they choose to go public with a vulnerability before the vulnerability is fully patched and shipped to customer. As such, much of the industry has moved away from the term "Responsible" to the term "Coordinated".

> Responsible Disclosure should be deprecated in favor of something focused on getting the job done, which is to improve security and to protect users and systems.
>
> \- From: "[Coordinated Vulnerability Disclosure: Bringing Balance to the Force](https://docs.microsoft.com/en-us/archive/blogs/ecostrat/coordinated-vulnerability-disclosure-bringing-balance-to-the-force)" by [Katie Moussouris](https://twitter.com/k8em0) in 2010.
 
Another really good point on this topic from CERT:

> **Who is Responsible Here?**
>
> You may be familiar with the term responsible disclosure [15] and wonder how it's different from CVD. The history of responsible disclosure makes for a long story best told over adult beverages at a hotel bar during a security conference, so we won't go into it here. Without belaboring the topic, the sticking point comes down to the fact that what constitutes "responsible" behavior is a matter of opinion that is always framed within the values of whoever is using the term. The vendors cry, "Disclosing a vulnerability without an available patch is not responsible!" "Not fixing this vulnerability quicker is not responsible!" the finders retort. Meanwhile, the deployer asks, "Who's responsible for fixing this?" while knowing the answer all too well. Because of the inherent value judgement and lack of agreement on its definition, the CERT/CC, along with numerous other organizations, advocates for the use of the term Coordinated Vulnerability Disclosure (CVD) [16,17] to reduce misunderstanding and promote cooperation.
> 
> \- https://vuls.cert.org/confluence/display/CVD/1.2.+CVD+Context+and+Terminology+Notes

**Comment by mcollina** [comment]
Thanks for this discussion, it's important that we talk about it.

I still think the term _responsible_ is good because some security researchers (including Google folks, unfortunately) are treating volunteer-based Open Source projects as vendors/companies.
In your message, it seems you are implying that Node.js is a GitHub product - which is not. We have no  direct funding per se and all the security work is very hard to justify from an investment perspective from volunteers (it's mostly silent). Therefore I think it's _irresponsible_ to disclose the vulnerability if the project asks for an extension. The researcher will be doing a disservice to the community.

I'm totally behind using a term "coordinated disclosure" when talking with a company.

(There are some private conversation about this topic I cannot disclose for now).

**Comment by DanielRuf** [comment]
> In your message, it seems you are implying that Node.js is a GitHub product

Regarding

> From the perspective of the company, in this case GitHub

Yes, that was something that confused me but I didn't mention.
npm inc (but not Node and all packages on npmjs) was bought by GitHub.

But this is not the case for
* Node.js
* OpenJS Foundation
* Node.js Foundation
* packages created by the community (where we, the WG, handled the triaging and disclosure process, but only for those)

**Comment by JLLeitschuh** [comment]
Yea, please forgive me on that one, I actually copied and pasted some of the contents of this message from a previous discussion I had with GitHub about their vulnerability disclosure program. It wasn't my intention to imply this was a project under GitHub.

> I still think the term responsible is good because some security researchers (including Google folks, unfortunately) are treating volunteer-based Open Source projects as vendors/companies.

IMHO, I, as a researcher, am in a similar boat to the OSS maintainer. I'm aware of a vulnerability in an OSS project, but may not know enough to actually fix it sufficiently. I also don't always have the funding to support getting the vulnerability fixed.

As the researcher, actually don't mind all that much if the maintainer fixes the vulnerability or not. If they do, I think it's probably better for the ecosystem, but if not what's more important is making the users of that library aware of the vulnerability (usually through CVE issuance). This may involve disclosure of a vulnerability without a fix. Is this "responsible"? Is the maintainer being irresponsible for not patching the vulnerability? I'd argue no.

Now, from my particular perspective and with my own personal moral compass, I believe I have a responsibility that if I find a vulnerability, then the information becomes public within a reasonable amount of time. But that's my own personal set of ethics and responsibilities. In general, I prefer the term "coordinated" because both my and the maintainers ethics and morals can exist in the vulnerability disclosure relationship without complications around "irresponsibility" being included in the dialogue.

**Comment by mhdawson** [comment]
For me 
>then the information becomes public within a reasonable amount of time.
is a key aspect.

If a vulnerability is reported to a project and they are not acting in good faith to work towards a resolution then disclosure is reasonable. If on the other hand they are acting in good faith and it just takes a longer time than people would like because things take longer in Open source projects with volunteers, then I don't think it's responsible. 

Further I think fixed deadlines do damage in a number of ways:
* It makes it too easy for those doing the disclosure. Disclosing without a patch should always be treated as a serious 
  event and the those disclosing should be willing to stand behind their justification as to why it is the right thing to do.
* They pressure volunteers to work outside the scope of what they likely volunteered for. The result ends up being  
   burn out for those involved, people avoiding getting involved in the first place, and longer term damage the project's
   ability to address vulnerabilities in a timely manner.

**Comment by mhdawson** [comment]
I don't think we are going to change our terminology in the short term. Closing this issue, please let us know if you think that was not the right thing to do.
